---
title: "h3 ACS percent error"
author: "Anonymous"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(janitor)
library(kableExtra)
library(cowplot)
```

# Defining Functions

### Functions to fit different types of curves

```{r}
#exponential decay
fit_exponential <- function(df, 
                            residual_col, 
                            intensity_col) {
  
  #extract relevant cols
  residual <- df[[residual_col]]
  intensity <- df[[intensity_col]]
  
  #define model formula
  model_formula <- residual ~ a * exp(-b * (intensity))
  
  #fit the model
  model<- tryCatch({
    nls(model_formula,
        start = list(a = max(residual), b = 0.01))
  }, error = function(e) {
    message("Model fitting failed: ", e$message)
  })
  
  return(model)
}

#power law decay
fit_power_law <- function(df, residual_col, intensity_col) {
  
  residual <- df[[residual_col]]
  intensity <- df[[intensity_col]]
  
  #define power law decay formula
  #model_formula <- residual ~ a * intensity^(-b) + c
  model_formula <- residual ~ a * intensity^(-b)
  
  #list start vals
  start_vals <- list(
    a = max(df$residual, na.rm = TRUE),
    b = 1
    #c = 0
  )
  
  #fit the model
  model <- tryCatch(
    nls(model_formula,
        data = df, 
        start = start_vals),
    error = function(e) {
      message("Model fitting failed: ", e$message)
    })
  
  return(model)
}

#log transformed linear model
fit_log <- function(df, residual_col, intensity_col) {
  
  residual <- df[[residual_col]]
  intensity <- df[[intensity_col]]
  
  #fit the model
  model <- tryCatch(
    lm(residual ~ log(intensity)), #this version for timed search
    error = function(e) {
      message("Model fitting failed: ", e$message)
    })
  
  return(model)
}

#linear model
fit_line <- function(df, residual_col, intensity_col) {
  
  residual <- df[[residual_col]]
  intensity <- df[[intensity_col]]
  
  #fit the model
  model <- tryCatch(
    lm(residual ~ intensity), 
    error = function(e) {
      message("Model fitting failed: ", e$message)
    })
  
  return(model)
}
```

## function to make prediction

```{r}
#function to predict values using the fitted model
exp_predict <- function(df, new_df, model_type = c("exp", "pwr", "log", "line"), residual_col, intensity_col) {
  
  #fit the correct model
  if(model_type == "exp") {
    model <- fit_exponential(df, residual_col, intensity_col)
  } 
  if(model_type == "pwr") {
    model <- fit_power_law(df, residual_col, intensity_col)
  } 
  if(model_type == "log") {
    model <- fit_log(df, residual_col, intensity_col)
  }
  if(model_type == "line") {
    model <- fit_line(df, residual_col, intensity_col)
  }
  
  #if model fits, generate predictions df
  if (!is.null(model)) {
    pred_df <- data.frame(
      intensity = new_df$intensity,
      predicted = predict(model, newdata = new_df),
      rse = summary(model)$sigma
    )
    return(pred_df)
  } else {
    failed_df <- new_df %>%
      mutate(group = NA) %>% 
      mutate(predicted = NA) %>% 
      mutate(rse = NA)
    
    return(failed_df)
  }
}
```

# Reading in Data and cleaning

```{r}
#for starting quadrats
new_dat <- data.frame(intensity = c(seq(0, 2000, length.out = 100)))

#reading in the data
h3_matern_acs <- read.csv("data/H3_matern_acs.csv")
h3_poisson_acs <- read.csv("data/H3_poisson_acs.csv") %>% 
  filter(Number.of.clumps == 5, Poisson.mean == 3)
h3_random_acs <- read.csv("data/H3_random_acs.csv")
```

```{r}
#bind data and do some cleaning
acs_clean <- rbind(h3_matern_acs, h3_poisson_acs, h3_random_acs) %>% 
  janitor::clean_names() %>% 
  mutate(spatial_distribution = case_when(
    spatial_distribution == "Clumped-Matern" ~ paste(matern_clump_placement), 
    T ~ spatial_distribution)) %>% 
  filter(detectability_of_rare_mussels == 1)


#calculate residual, prop found, m sampled, density category
acs_residual <- acs_clean %>% 
  mutate(residual = (abs(hh_metric-true_mussel_density)/true_mussel_density) * 100) %>%
  mutate(proportion_found = total_mussels_detected/total_mussels) %>% 
  mutate(m_sampled = total_quadrats_sampled/4) %>% 
  mutate(density_cat = case_when(true_mussel_density %in% c(0.1, 0.01) ~ "rare", T ~ "common"))
```

# Starting Quadrats

## quick plot

```{r}
acs_grouped <- acs_residual %>% 
  group_by(spatial_distribution, density_cat, acs_num_quadrats) %>% 
  summarise(mean_pe = mean(residual))

ggplot(data = acs_grouped) +
   geom_point(aes(x = acs_num_quadrats, y = mean_pe, 
                 color = spatial_distribution, shape = density_cat)) +
  geom_line(aes(x = acs_num_quadrats, y = mean_pe, 
                colour = spatial_distribution, linetype = density_cat)) +
  scale_y_continuous(limits = c(0, 200)) 
```


## Generate Predictions

```{r}
#exp
acs_exp_model_preds <- acs_residual %>%
  group_by(spatial_distribution, density_cat) %>%
  group_modify( ~ exp_predict(.x, new_df = new_dat, model_type = "exp", 
                              residual = "residual", 
                              intensity = "acs_num_quadrats"))

#pwr
acs_pwr_model_preds <- acs_residual %>%
  group_by(spatial_distribution, density_cat) %>%
  group_modify( ~ exp_predict(.x, new_df = new_dat, model_type = "pwr", 
                              residual = "residual", 
                              intensity = "acs_num_quadrats"))

#log
acs_log_model_preds <- acs_residual %>%
  group_by(spatial_distribution, density_cat) %>%
  group_modify( ~ exp_predict(.x, new_df = new_dat, model_type = "log", 
                              residual = "residual", 
                              intensity = "acs_num_quadrats"))

#linear
acs_line_model_preds <- acs_residual %>%
  group_by(spatial_distribution, density_cat) %>%
  group_modify( ~ exp_predict(.x, new_df = new_dat, model_type = "line", 
                              residual = "residual", 
                              intensity = "acs_num_quadrats"))
```

## table of best predictions

```{r warning=FALSE, message=FALSE}
#bind RSE into table
acs_rse_table <- data.frame(
  spatial_distribution = c(acs_line_model_preds$spatial_distribution),
  density = c(acs_line_model_preds$density_cat),
  exp_rse= c(acs_exp_model_preds$rse),
  pwr_rse= c(acs_pwr_model_preds$rse),
  log_rse = c(acs_log_model_preds$rse),
  line_rse = c(acs_line_model_preds$rse)) %>% 
  distinct()

#add column which has min rse model name
y <- colnames(acs_rse_table)[apply(acs_rse_table[,c(3:6)],1,which.min) + 2]
acs_rse_table$min_col <- y

knitr::kable(acs_rse_table) %>% 
  kable_styling()
```

## figure of best predictions

```{r}
#bind RSE into table
acs_best_fit_preds <- rbind(
  acs_exp_model_preds,
  acs_pwr_model_preds,
  acs_log_model_preds,
  acs_line_model_preds
) %>% 
  group_by(spatial_distribution, density_cat, intensity) %>% 
  slice_min(order_by = rse, n = 1, with_ties = T)

# Plot the data and fitted curves
acs_pe_starting <- 
  ggplot() +
  geom_line(data = acs_best_fit_preds, 
            aes(x = intensity, y = predicted,
                linetype = density_cat,
                color = spatial_distribution),
            linewidth = 1) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(title = "Adaptive Cluster Sample",
       x = "Number of Starting Quadrats",
       y = "Percent Error in\nEstimated Density") +
  scale_color_manual(name = "Mussel Spatial Distribution",
                     values = c("random" = "#CC79A7", 
                                "Clumped-Poisson" = "#D55E00",
                                "One shore only" = "#E69F00",
                                "One shore; one middle" = "#56B4E9",
                                "One shore; one middle; 2 additional" = "#009E73",
                                "One shore; 2 additional" = "#F0E442",
                                "Randomly placed" = "#0072B2"),
                     labels = c("random" = "Random", 
                                "Clumped-Poisson" = "Poisson",
                                "One shore only" = "Clumped Matern 1S",
                                "One shore; one middle" = "Clumped Matern 1S+1M",
                                "One shore; one middle; 2 additional" = "Clumped Matern 1S+1M+2",
                                "One shore; 2 additional" = "Clumped Matern 1S+2", 
                                "Randomly placed" = "Clumped Matern 3"),
                     limits = c("random", 
                                "Clumped-Poisson", 
                                "One shore only", 
                                "One shore; one middle", 
                                "One shore; one middle; 2 additional", 
                                "One shore; 2 additional", 
                                "Randomly placed")) +
  scale_linetype_manual(name = "Mussel Density",
    values = c("rare" = "dashed", "common" = "solid")) +
  theme_minimal() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

ggsave("figures/H3_ACS_pe_starting_quads.png", plot = acs_pe_starting, width = 12, height = 8)
```

# Average Quadrats

```{r}
acs_avg <- acs_residual %>% 
  group_by(acs_num_quadrats, density_cat, spatial_distribution) %>% 
  mutate(mean_total_quads = mean(total_quadrats_sampled)) %>% 
  ungroup()
```

## Quick Plot

```{r}
acs_grouped <- acs_avg %>% 
  group_by(mean_total_quads, spatial_distribution, density_cat) %>% 
  summarise(mean_pe = mean(residual))

ggplot(data = acs_grouped) +
   geom_point(aes(x = mean_total_quads, y = mean_pe, 
                 color = spatial_distribution, shape = density_cat)) +
  geom_line(aes(x = mean_total_quads, y = mean_pe, 
                colour = spatial_distribution, linetype = density_cat)) +
  scale_y_continuous(limits = c(0, 200)) 
```

## Generate Predictions

```{r}
#exp
acs_exp_model_preds <- acs_avg %>%
  group_by(spatial_distribution, density_cat) %>%
  group_modify( ~ exp_predict(.x, new_df = new_dat, model_type = "exp", 
                              residual = "residual", 
                              intensity = "mean_total_quads"))

#pwr
acs_pwr_model_preds <- acs_avg %>%
  group_by(spatial_distribution, density_cat) %>%
  group_modify( ~ exp_predict(.x, new_df = new_dat, model_type = "pwr", 
                              residual = "residual", 
                              intensity = "mean_total_quads"))

#log
acs_log_model_preds <- acs_avg %>%
  group_by(spatial_distribution, density_cat) %>%
  group_modify( ~ exp_predict(.x, new_df = new_dat, model_type = "log", 
                              residual = "residual", 
                              intensity = "mean_total_quads"))

#linear
acs_line_model_preds <- acs_avg %>%
  group_by(spatial_distribution, density_cat) %>%
  group_modify( ~ exp_predict(.x, new_df = new_dat, model_type = "line", 
                              residual = "residual", 
                              intensity = "mean_total_quads"))
```

## table of best predictions

```{r warning=FALSE, message=FALSE}
#bind RSE into table
acs_rse_table <- data.frame(
  spatial_distribution = c(acs_line_model_preds$spatial_distribution),
  density = c(acs_line_model_preds$density_cat),
  exp_rse= c(acs_exp_model_preds$rse),
  pwr_rse= c(acs_pwr_model_preds$rse),
  log_rse = c(acs_log_model_preds$rse),
  line_rse = c(acs_line_model_preds$rse)) %>% 
  distinct()

#add column which has min rse model name
y <- colnames(acs_rse_table)[apply(acs_rse_table[,c(3:6)],1,which.min) + 2]
acs_rse_table$min_col <- y

knitr::kable(acs_rse_table) %>% 
  kable_styling()
```

## figure of best predictions

```{r}
#bind RSE into table
acs_best_fit_preds <- rbind(
  acs_exp_model_preds,
  acs_pwr_model_preds,
  acs_log_model_preds,
  acs_line_model_preds
) %>% 
  group_by(spatial_distribution, density_cat, intensity) %>% 
  slice_min(order_by = rse, n = 1, with_ties = T)

# Plot the data and fitted curves
acs_pe_avg <- 
  ggplot() +
  geom_line(data = acs_best_fit_preds, 
            aes(x = intensity, y = predicted,
                linetype = density_cat,
                color = spatial_distribution),
            linewidth = 1) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(title = "Adaptive Cluster Sample",
       x = "Mean Number of Total Quadrats",
       y = "Percent Error in\nEstimated Density") +
  scale_color_manual(name = "Mussel Spatial Distribution",
                     values = c("random" = "#CC79A7", 
                                "Clumped-Poisson" = "#D55E00",
                                "One shore only" = "#E69F00",
                                "One shore; one middle" = "#56B4E9",
                                "One shore; one middle; 2 additional" = "#009E73",
                                "One shore; 2 additional" = "#F0E442",
                                "Randomly placed" = "#0072B2"),
                     labels = c("random" = "Random", 
                                "Clumped-Poisson" = "Poisson",
                                "One shore only" = "Clumped Matern 1S",
                                "One shore; one middle" = "Clumped Matern 1S+1M",
                                "One shore; one middle; 2 additional" = "Clumped Matern 1S+1M+2",
                                "One shore; 2 additional" = "Clumped Matern 1S+2", 
                                "Randomly placed" = "Clumped Matern 3"),
                     limits = c("random", 
                                "Clumped-Poisson", 
                                "One shore only", 
                                "One shore; one middle", 
                                "One shore; one middle; 2 additional", 
                                "One shore; 2 additional", 
                                "Randomly placed")) +
  scale_linetype_manual(name = "Mussel Density",
    values = c("rare" = "dashed", "common" = "solid")) +
  theme_minimal() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

ggsave("figures/H3_ACS_pe_avg_quads.png", plot = acs_pe_avg, width = 12, height = 8)
```
